jamesrochabrun/SwiftOpenAI

Sources/OpenAI/Public/Parameters/Runs/RunToolsOutputParameter.swift

RunToolsOutputParameter.ToolOutput' initializer is inaccessible due to 'internal' protection level

RunToolsOutputParameter.ToolOutput' initializer is inaccessible due to 'internal' protection level

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj/project.pbxproj

The sample project at `Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj` now references the local SPM package at the root of the repo. This makes it easier to make changes to the SPM package while working within the sample project. There are two major differences:
1. The dependency on SwiftOpenAI is added using a 'local package' at `File > Add Package Dependencies`:
2. Occasionally Xcode stops tracking the changes accurately when modifying SwiftOpenAI from within the SwiftOpenAIExample project. If that happens to you, go to `File > Packages > Reset Package Caches`

Made the sample app reference local SPM package

---

Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift

Adds `AIProxyService` as a conformer of `OpenAIService`. I followed the precedent set by the Azure contribution and added AIProxy-specific files to the `Sources/OpenAI/AIProxy` folder. I managed to get the changes down to just these two files:
```
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
```
You will see that `AIProxyService.swift` is heavily modeled after `DefaultOpenAIService.swift`.
Instances of AIProxyService can be created with the following:
```
var service = AIProxyService(
partialKey: "<snip>"
)
#if DEBUG && targetEnvironment(simulator)
service.deviceCheckBypass = "<snip>"
#endif
```
I have tested all functionality in the sample app in the `SwiftOpenAIExample` Xcode project. The easiest way to test is to follow the integration guide …

Added support for AI Proxy

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj/project.pbxproj
Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ServiceSelectionView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/SwiftOpenAIExampleApp.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

- In the SwiftOpenAI lib, makes AIProxyService accessible through `OpenAIServiceFactory.service(aiproxyPartialKey:aiproxyDeviceCheckBypass:)`
- In the SwiftOpenAIExample sample app, makes `ServiceSelectionView` the first as the first view of the sample app. Users can select 'Default OpenAI Service' or 'AI Proxy Service'. The selection pushes a new view into the stack that collects credentials based on the user's choice.

Added AI Proxy support to the sample app

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ServiceSelectionView.swift
README.md
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

- Added a new section with details about AIProxy, and linked it from the table-of-contents
- Added a blurb about protecting your key to the `getting-an-api-key` section
- Fixed a table-of-contents link to the Azure section
- The code changes are for consistent spelling of "AI Proxy"

Added AIProxy details to the README

---

Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift

Requests to AIProxy can be rate limited or rejected based on a client identifier. For example, if an app owner sees that a specific client is abusing their app (violating the terms), they can ban their client from AIProxy's developer dashboard.
This patch puts a client header in place, `aiproxy-client-id`, that is populated on both iOS and macOS.
The iOS client identifier comes from UIKit's `identifierForVendor`. Unfortunately, macOS does not have a comparable convenience method. As a workaround, I have followed Apple's sample code [here](https://developer.apple.com/documentation/appstorereceipts/validating_receipts_on_the_device#3744656)

Added macOS identifier for calls to AIProxy

---

Sources/OpenAI/Public/Shared/ResponseFormat.swift
Sources/OpenAI/Public/Shared/ToolChoice.swift
Tests/OpenAITests/OpenAITests.swift

The `response_format` and `tool_choice` fields of an assistant's run can either be objects or strings.
Previously, if the `tool_choice` was a string (e.g. 'auto') in the run response, we failed to decode the response. Similarly, if the `responses_type` was a string (e.g. 'auto') in the run response, we failed to decode the response.
This bug was reported by @mbrian23, with a full repro here. Thank you Martin!
https://gist.github.com/mbrian23/6863ffa705ccbb5097bd07efb2355a30
I added regression tests for the failing case.
References:
https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-response_format
https://platform.openai.com/docs/api-reference/runs/createRun#runs-createrun-tool_choice

Fix decoding error on assistants response

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/ChatDemo/ChatDemoView.swift
README.md
Sources/OpenAI/Public/Parameters/Model.swift

- Adds support for the omicron model
- Modifies the SwiftOpenAIExample ChatDemo to use gpt-4o
- Updates readme snippets to use gpt-4o

Update to gpt-4o

---

Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/Azure/AzureOpenAIAPI.swift
Sources/OpenAI/Azure/AzureOpenAIConfiguration.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/Private/Networking/Endpoint.swift
Sources/OpenAI/Private/Networking/OpenAIAPI.swift
Sources/OpenAI/Public/Parameters/Assistant/AssistantParameters.swift
Sources/OpenAI/Public/Parameters/VectorStore/VectorStoreParameter.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIService.swift

Assistants API + Azure
```swift
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference?tabs=python
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/assistant
case assistant(AssistantCategory)
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions
case chat(deploymentID: String)
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference-messages?tabs=python
case message(MessageCategory)
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference-runs?tabs=python
case run(RunCategory)
/// https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference-runs?tabs=python#list-run-steps
case runStep(RunStepCategory)
/// …
```

Assistants API support for Azure 

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/Assistants/AssistantThreadConfigurationProvider.swift
Sources/OpenAI/Public/ResponseModels/Assistants/AssistantStreamEvent.swift
Sources/OpenAI/Public/ResponseModels/Assistants/AssistantStreamEventObject.swift
Sources/OpenAI/Public/Service/OpenAIService.swift

Decoding run stream events
```swift
let decoded = try self.decoder.decode(RunObject.self, from: data)
switch RunObject.Status(rawValue: decoded.status) {
case .queued:
continuation.yield(.threadRunQueued(decoded))
case .inProgress:
continuation.yield(.threadRunInProgress(decoded))
case .requiresAction:
continuation.yield(.threadRunRequiresAction(decoded))
case .cancelling:
continuation.yield(.threadRunCancelling(decoded))
case .cancelled:
continuation.yield(.threadRunCancelled(decoded))
case .failed:
continuation.yield(.threadRunFailed(decoded))
case .completed:
continuation.yield(.threadRunCompleted(decoded))
case .expired:
continuation.yield(.threadRunExpired(decoded))
```

Decoding run stream events

---

Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/Public/Parameters/Chat/ChatCompletionParameters.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift

- On June 6th OpenAI announced that streaming chat completions now support usage details. Previously, usage details were only available on non-streaming chat completions.
- This patch makes streaming chat completions default to include usage details. The final chunk of each streaming response looks like this (note the `prompt_tokens`, `completion_tokens`, and `total_tokens` lines):
```
data: {"id":"chatcmpl-9YM1lpTbJLDBnrawPqt2CjT3gnoVA","object":"chat.completion.chunk","created":1717974853,"model":"gpt-4o-2024-05-13","system_fingerprint":"fp_319be4768e","choices":[],"usage":{"prompt_tokens":11,"completion_tokens":20,"total_tokens":31}}
```
I have enabled this option by default in all three services (DefaultOpenAIService, DefaultOpenAIAzureService, and AIProxyService).

Add usage details to streaming chat completions

---

README.md
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

* This patch only affects AIProxy customers, and can be safely ignored for users of SwiftOpenAI's default service.
* Requests to AIProxy can be annotated with a developer's own client IDs. This is handy for customer that already have analytics IDs that they'd like to reuse between their existing system and AIProxy. Requests are annotated in the AIProxy dashboard under both the 'Top client usage' tab and the 'Requests' tab.
* Passing an `aiproxyClientID` argument to the service instantiation will thread the client ID through to all requests made by that service. For example, your initialization code may become:
```swift
let myService = OpenAIServiceFactory.service(aiproxyPartialKey: partialKey,
aiproxyClientID: 'my-awesome-id')
```
And then requests from `myService` will be annotated in …

Add AIProxy support for annotating requests with custom client IDs

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj/project.pbxproj
Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ApiKeyIntroView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/LocalChatDemo/LocalChatDemoView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/LocalHostEntryView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/OptionsListView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ServiceSelectionView.swift
Sources/OpenAI/Private/Networking/OpenAIAPI.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

Ollama OpenAI compatibility

---

Sources/OpenAI/AIProxy/AIProxyCertificatePinning.swift
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/Public/Service/OpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

* Requests to AIProxy only succeed if we recognize the public certificate used in establishing the tls handshake. This makes performing a MITM attack more challenging. MITM is a common tactic against mobile apps because the attacker controls the hardware. They can use desktop proxy software to MITM an app and decrypt the https requests as they go by (this requires installing a trusted certificate on the attacker's phone, which is also trivial).
* This is one additional layer of security in our defense against API abuse.
* The majority of this patch only impacts AIProxy-specific code, however there are two spots where a change was required to the core codebase. I will highlight each with a comment. For details about why they were changed (which I consider an Apple bug) please see the …

Add AIProxy support for certificate pinning

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
README.md
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

- The DeviceCheck bypass token is used for AIProxy customers to make requests to AIProxy from the iOS simulator, where DeviceCheck is not available.
- If the token leaks into a production build of the app, then attackers can use the bypass token themselves to skip one layer of security that AIProxy provides.
- This patch adjusts the way that developers set the bypass token, removing it from the source code and adding it instead as an env variable. Env variables are not packaged up in distribution app bundles, and are therefore harder to make leak into a production release of your app.
- Updated the README with new instructions for adding the `AIPROXY_DEVICE_CHECK_BYPASS` env variable

Set AIProxy DeviceCheck bypass token as env variable

---

Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift

The submitOutput function was sending wrong parameters where stream was false , because of this the response was an empty stream object. Just fixed it by passing runToolsOutputParameter.

Fixed SubmitToolsOutput Function

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
README.md
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

- Starting next week, all AIProxy integrations will require a service URL. Developers each get their own service URL to proxy requests through. The service URL is displayed in the AIProxy dashboard when you configure your project.
- The AIProxy integration code changes from this:
```swift
let service = OpenAIServiceFactory.service(
aiproxyPartialKey: "your_partial_key_goes_here"
)
```
to this:
```swift
let service = OpenAIServiceFactory.service(
aiproxyPartialKey: "your_partial_key_goes_here",
aiproxyServiceURL: "your_service_url_goes_here"
)

Add serviceURL to AIProxy integration

---

Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift

- If the developer does not provide an AIProxy `serviceURL` in their integration, we want to fall back to `api.aiproxy.pro` and not `http://Lous-MacBook-Air-3.local:4000` 😅
- I introduced this bug in https://github.com/jamesrochabrun/SwiftOpenAI/pull/63

AIProxy bug fix: Do not fall back to Lou's computer

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/ApiKeyIntroView.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/Public/Parameters/Chat/ChatCompletionParameters.swift

Solves https://github.com/jamesrochabrun/SwiftOpenAI/issues/67
Issue:
Azure API reference does not support stream options as parameter.
https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

Fix for azure stream options

---

Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

When trying to set the service as a member on a type, you can hit the compilation error: 
```
Property definition has inferred type 'some OpenAIService', involving the 'some' return type of another declaration
```
To work around the compilation error, I could specify `let service: some OpenAIService = ...`. A better fix, though, is to remove the `some` keyword on the factory methods. We don't need `some` here, because the protocol that our concrete types are conforming to is not a PAT. We don't need to use 'reverse generics' and can instead just rely on vanilla polymorphism through protocols.

Remove 'some' from factory return type

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/AIProxyIntroView.swift
README.md
Sources/OpenAI/AIProxy/AIProxyService.swift

- Made the AIProxy section of the readme consistent with SwiftAnthropic's readme
- Added a `canProceed` helper to the intro view that ensures both the serviceURL and partialKey are entered by the user

Touch up the AIProxy section of README

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj/project.pbxproj
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ChatStructureOutputTool/ChatStructureOutputToolDemoView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ChatStructureOutputTool/ChatStructuredOutputToolProvider.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ChatStructuredOutputs/ChatStructuredOutputDemoView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/OptionsListView.swift
Sources/OpenAI/Public/Shared/JSONSchema.swift

- Support for Structure outputs in tools
- Handling recursive schemas
- Handling optional values in Schemas

Support for Structure outputs in tools

---

README.md

1. Function calling: Structured Outputs via tools is available by setting strict: true within your function definition. This feature works with all models that support tools, including all models gpt-4-0613 and gpt-3.5-turbo-0613 and later. When Structured Outputs are enabled, model outputs will match the supplied tool definition.
Using this schema:
```json
{
"schema": {
"type": "object",
"properties": {
"steps": {
"type": "array",
"items": {
"type": "object",
"properties": {
"explanation": {
"type": "string"
},
"output": {
"type": "string"
}
},
"required": ["explanation", "output"],
"additionalProperties": false
}
},
"final_answer": {
"type": "string"
}
},
"required": ["steps", "final_answer"],
"additionalProperties": false
}
}
```
You can use the convenient `JSONSchema` object like …

Updating READ.me

---

Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/Azure/AzureOpenAIAPI.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/LocalModelService/LocalModelService.swift
Sources/OpenAI/Private/Networking/OpenAIAPI.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIService.swift
Sources/OpenAI/Public/Shared/MessageAttachment.swift

Addresses 
https://github.com/jamesrochabrun/SwiftOpenAI/issues/85
https://github.com/jamesrochabrun/SwiftOpenAI/issues/86

Issues 85, 86

---

Sources/OpenAI/Public/ResponseModels/Messages/MessageContent.swift

When the Assistants API is asked to search a file store, it replies with a response that does not include properties required by the MessageObject's CodingKeys. This leads to a decoding error. This PR makes those values optional so that:
1. Current Assistants API responses that are successfully decoded are still decoded successfully
2. Assistants API responses with data from a file_search, which do not contain `FileCitation.type`, `FileCitation.text`, `FileCitation.startIndex`, and `FileCitation.endIndex`, also work
**TEST PLAN**
1. Create an Assistant AI in OpenAI and note its `agent_id`. Attach a file store with at least one text file.
2. Create a skeleton project that utilizes SwiftOpenAI's current `main` branch to handle an Assistant interaction, such as in a conversation.
3. Create a …

Fix decoding error triggered by Assistants API responses with data from searching a vector database

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample.xcodeproj/project.pbxproj
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ChatDemo/ChatDemoView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/OverridableURLProxyPathIntroView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/ServiceSelectionView.swift
README.md
Sources/OpenAI/Private/Networking/OpenAIAPI.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

Groq API is mostly compatible with OpenAI's client libraries like `SwiftOpenAI` to use Groq using this library you just need to create an instance of `OpenAIService` like this:
```swift
let apiKey = "your_api_key"
let service = OpenAIServiceFactory.service(apiKey: apiKey, overrideBaseURL: "https://api.groq.com/", proxyPath: "openai")
```
For Supported API's using Groq visit its [documentation](https://console.groq.com/docs/openai).
⚠️ Note: You can probably use the `OpenAIServiceFactory.service(apiKey:overrideBaseURL:proxyPath)` for any OpenAI compatible service.

Groq support

---

README.md
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

Consumers now can pass additional parameters in to the request. e.g Open Router:
```swift
let service = OpenAIServiceFactory.service(
apikey:  "${OPENROUTER_API_KEY}",  
baseURL: "https://openrouter.ai",
proxyPath: "api"
headers: ["HTTP-Referer":  "${YOUR_SITE_URL}",  "X-Title":  "${YOUR_SITE_NAME}")
```

Adding additional parameters in API.

---

Sources/OpenAI/Public/ResponseModels/Messages/MessageContent.swift

This PR extend Message Content response with Image url type.
OpenAI image url message response structure:

Message Content - added image url response type

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/LocalChatDemo/LocalChatDemoView.swift
Examples/SwiftOpenAIExample/SwiftOpenAIExample/LocalHostEntryView.swift
Sources/OpenAI/AIProxy/AIProxyService.swift
Sources/OpenAI/AIProxy/Endpoint+AIProxy.swift
Sources/OpenAI/Azure/AzureOpenAIAPI.swift
Sources/OpenAI/Azure/DefaultOpenAIAzureService.swift
Sources/OpenAI/LocalModelService/LocalModelAPI.swift
Sources/OpenAI/LocalModelService/LocalModelService.swift
Sources/OpenAI/Private/Networking/Endpoint.swift
Sources/OpenAI/Private/Networking/OpenAIAPI.swift
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

Having static properties in the `OpenAIAPI` enum was a bad coding choice, this choice was took aiming to support so many configurations, such Gemini, Groq etc support.
This is a large change but will make the library more scalable.
Changes has been done commit by commit for each service, Azure, Ollama, OpenAI and AIProxy

Removing Static properties from OpenAI API

---

Examples/SwiftOpenAIExample/SwiftOpenAIExample/ApiKeyIntroView.swift
README.md

The [DeepSeek](https://api-docs.deepseek.com/) API uses an API format compatible with OpenAI. By modifying the configuration, you can use SwiftOpenAI to access the DeepSeek API.
```swift
// Creating the service
let apiKey = "your_api_key"
let service = OpenAIServiceFactory.service(
apiKey: apiKey,
overrideBaseURL: "https://api.deepseek.com")
// Making a request
let prompt = "What is the Manhattan project?"
let parameters = ChatCompletionParameters(messages: [.init(role: .user, content: .text(prompt))], model: .custom("deepseek-reasoner"))
let stream = service.startStreamedChat(parameters: parameters)
```
For more inofrmation about the `DeepSeek` api visit its [documentation](https://api-docs.deepseek.com).

DeepSeek demo

---

README.md
Sources/OpenAI/Public/Service/DefaultOpenAIService.swift
Sources/OpenAI/Public/Service/OpenAIServiceFactory.swift

For reasoning models, ensure that you extend the timeoutIntervalForRequest in the URL session configuration to a higher value. The default is 60 seconds, which may be insufficient, as requests to reasoning models can take longer to process and respond.
To configure it:
```swift
let apiKey = "your_openai_api_key_here"
let organizationID = "your_organization_id"
let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForRequest = 360 // e.g., 360 seconds or more.
let service = OpenAIServiceFactory.service(apiKey: apiKey, organizationID: organizationID, configuration: configuration)
```

Adding configuration instruction to READ.me

---

Sources/OpenAI/Public/Parameters/Message/MessageParameter.swift

ContentItem.text should contain String instead of object
Currently it sends following JSON:
```
{
"content" : [
{
"type" : "text",
"text" : {
"type": "text",
"text": "Where is this photo taken?"
}
},
{
"type" : "image_file",
"image_file" : {
"file_id" : "file-LY37xeG7327xbghdpij6mW"
}
}
],
"role" : "user"
}
```
Should be
```
{
"content" : [
{
"type" : "text",
"text" : "Where is this photo taken?"
},
{
"type" : "image_file",
"image_file" : {
"file_id" : "file-LY37xeG7327xbghdpij6mW"
}
}
],
"role" : "user"
}
```
See https://platform.openai.com/docs/api-reference/messages/createMessage

Fix MessageParameter for "Create message" request

---

README.md
Sources/OpenAI/Public/ResponseModels/Response/ResponseModel.swift
Tests/OpenAITests/OpenAITests.swift

- Adding tests for `ResponseModel`
- Adding computed `outputText`
```swift
/// Convenience property that aggregates all text output from output_text items in the output array.
/// Similar to the outputText property in Python and JavaScript SDKs.
public var outputText: String? {
let outputTextItems = output.compactMap { outputItem -> String? in
switch outputItem {
case .message(let message):
return message.content.compactMap { contentItem -> String? in
switch contentItem {
case .outputText(let outputText):
return outputText.text
}
}.joined()
default:
return nil
}
}
return outputTextItems.isEmpty ? nil : outputTextItems.joined()
}
```

Support for text output + tests

---

README.md
Sources/OpenAI/Public/Parameters/Audio/AudioTranscriptionParameters.swift
Sources/OpenAI/Public/Parameters/Audio/AudioTranslationParameters.swift
Sources/OpenAI/Public/Parameters/Chat/ChatCompletionParameters.swift
Sources/OpenAI/Public/ResponseModels/Response/ResponseModel.swift

Codable updates

---

Sources/OpenAI/Public/ResponseModels/Model/ModelObject.swift

Model List API for DeepSeek or Gemini, 'created' is not return.

feaT: update for model list compatible

---

Sources/OpenAI/Public/Service/OpenAIService.swift

The streaming methods (fetchStream and fetchAssistantStreamEvents) don't decode OpenAI error responses, only returning generic "status code X" messages instead of detailed error information.
Apply the same OpenAI error decoding logic from the working fetch method to both streaming methods.
This PRs also modifies the `errorMessage` to keep the original error message from API server, giving application full control over how to construct the final error message. Rationale: I think at library-level, we should not modify the error message from remote API server. This would make it very difficult at the app-level  to offer good error reporting UX.

Api error details

---

Sources/OpenAI/Public/ResponseModels/Model/ModelObject.swift

The model listing call fails when for OpenRouter. Reason: OpenRouter doesn't include these fields in their response.
This PR makes ModelObject's `object` and `ownedBy` fields optional.
A long-term solution is probably asking OpenRouter to fix their response.

Fix model listing issues for OpenRouter
